config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/dashboard', to: 'general#index', as: 'dashboard'
    post '/create', to: 'general#create'

    get '/', to: 'general#index'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Users ###
    get '/user/:id', to: 'general#show_user', as: 'show_user'
    delete '/user/:id', to: 'general#delete_user', as: 'delete_user'
    post '/user/:id/validate', to: 'general#validate_user', as: 'validate_user'
    post '/user/:id/invalidate', to: 'general#invalidate_user', as: 'invalidate_user'

    ### Auditor ###
    post '/auditor/set_default_rating', to: 'general#set_default_auditor_rating', as: 'set_default_auditor_rating'
    post '/auditor/:id/download_cv', to: 'general#download_cv', as: 'download_auditor_cv'

    ### Audits ###
    get '/audit/:id/show', to: 'general#show_audit', as: 'show_audit'
    post '/audit/:id/validate', to: 'general#validate_audit', as: 'validate_audit'
    post '/audit/:id/invalidate', to: 'general#invalidate_audit', as: 'invalidate_audit'
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Report ###
    post '/report/set_default_rating', to: 'general#set_default_report_rating', as: 'set_default_report_rating'

    ### Notifications ###
    get '/notification/:id/show', to: 'general#show_notification', as: 'show_notification'

    ### Requests ###
    get '/request/:id/show', to: 'general#show_request', as: 'show_request'

    ### Terms ###
    resources :terms, controller: "terms"
    post 'terms/:id/select', to: "terms#select", as: "term_select"

    ### Contracts ###
    resources :contracts, controller: "contracts"
    post 'contracts/:id/select', to: "contracts#select", as: "contract_select"
    post 'contracts/:id/download', to: "contracts#download", as: "contract_download"
  end

  namespace :client do
    get '/', to: 'general#index', as: 'dashboard'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'
    post '/purchases/:id/rate', to: 'general#rate_purchase', as: 'rate_purchase'
    get '/purchase/:id/auditor', to: 'general#show_auditor', as: 'purchase_auditor'
    post '/purchase/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'
    get '/reservation/:id/auditor', to: 'general#show_auditor', as: 'reservation_auditor'

    scope :audits do
      get '/search', to: 'audits#search'
      get '/advanced_search', to: 'audits#advanced_search'

      ### Purchase ###
      get '/purchase/:id/preview', to: 'audits#purchase_preview', as: 'purchase_preview'
      get '/purchase/:id', to: 'audits#purchase', as: 'purchase'

      ### Reserve ###
      get '/reserve/:id/preview', to: 'audits#reserve_preview', as: 'reserve_preview'
      get '/reserve/:id', to: 'audits#reserve', as: 'reserve'

      ### Request ###
      get '/request', to: 'audits#make_request'
      post '/request', to: 'audits#request_send'
    end
  end

  get '/auditor', to: 'auditor/general#index'

  namespace :auditor do
    root 'general#index'
    get '/', to: 'general#index', as: 'dashboard'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    post '/profile/download_cv', to: 'general#download_cv', as: 'download_cv'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    post '/accept_terms', to: 'general#accept_terms'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Audits ###
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'

    ### Clients ###
    get '/show_client/:id', to: 'general#show_client', as: 'show_client'

    scope :audits do
      ### Report ###
      get '/show_report/:id', to: 'audits#show_report', as: 'show_report'
      get '/report', to: 'audits#report'
      post '/report', to: 'audits#report_send'
      get '/reports', to: 'audits#reports'

      ### Plan ###
      get '/show_plan/:id', to: 'audits#show_plan', as: 'show_plan'
      get '/plan', to: 'audits#plan'
      post '/plan', to: 'audits#plan_send'
      get '/plans', to: 'audits#plans'
    end
  end

  scope :paypal, as: 'paypal' do
    post '/checkout', to: 'paypal#checkout'
    post '/execute', to: 'paypal#execute'
  end

  get '/sign_in', to: 'website#new', as: 'sign_in'
  get '/sign_out', to: 'website#destroy', as: 'sign_out'
  get '/terms', to: 'website#terms', as: 'terms'
  post '/sign_in', to: 'website#create'
  post '/accept_terms', to: 'website#accept_terms'

  get '/new_forgot_password', to: 'website#new_forgot_password'
  post '/create_forgot_password', to: 'website#create_forgot_password'
  get '/new_credentials/:token', to: 'website#new_credentials', as: 'new_credentials'

  root 'website#index'
end

app/models/audit.rb
class Audit < ApplicationRecord
  # Relationships
  belongs_to :auditor
  has_many :messages, dependent: :destroy

  # Validations
  validates_presence_of :products, :date, :auditor, :price, :summary

  # Scopes
  scope :validated, -> { where(validated: true)}
  scope :paginate, -> (page, per_page) { page(page).per(per_page) }
  scope :products_like, -> (query) { where("products ILIKE '%#{query}%'") }
end

app/models/client.rb
class Client < NormalUser
  has_many :requests, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :reservations, dependent: :destroy

  def prefix
    'cus'
  end
end

app/controllers/auditor/audits_controller.rb
class Auditor::AuditsController < ApplicationController
  before_action :auditor_authenticated?
  before_action :user_validated?

  layout 'auditor'

  def report
    @report = Report.new
  end

  def report_send
    @report = Report.new(report_params)

    if @report.save
      redirect_to auditor_reports_path, notice: "Report sent successfully"
    else
      render :report
    end
  end

  def reports
    @reports = @auditor.reports.order(:date)
  end

  def show_report
    @report = Report.find(params[:id])
  end

  def plan
    @plan = Plan.new
  end

  def plan_send
    @plan = Plan.new(plan_params)

    if @plan.save
      redirect_to auditor_plans_path, notice: "Plan sent successfully"
    else
      render :plan
    end
  end

  def plans
    @plans = @auditor.plans.order(:date)
  end

  def show_plan
    @plan = Plan.find(params[:id])
  end

  private
    def report_params
      params.require(:report)
        .permit(:products, :price, :summary, :report).merge(auditor_id: @auditor.id)
    end

    def plan_params
      params.require(:plan)
        .permit(:products, :price, :date, :summary, :fee).merge(auditor_id: @auditor.id)
    end
end

app/controllers/client/audits_controller.rb
class Client::AuditsController < ApplicationController
  before_action :client_authenticated?
  before_action :user_validated?

  layout 'client'

  def search
    @search_query = params[:query]

    if params[:query] && !params[:query].empty?
      reports = Report.products_like(params[:query])
      plans = Plan.products_like(params[:query])

      Auditor.company_address_like(params[:query]).each do |auditor|
        reports = reports.or(auditor.reports)
        plans = plans.or(auditor.plans)
      end
    else
      reports = Report.all
      plans = Plan.all
    end

    @reports = reports.validated().paginate(params[:report_page], 5)
    @plans = plans.validated().not_expired().paginate(params[:report_page], 5)
  end

  def advanced_search
    @search_company = params[:company]
    @search_address = params[:address]
    @search_products = params[:products]

    reports = Report.validated()
    plans = Plan.validated().not_expired()

    unless params[:products].empty?
      reports = reports.products_like(params[:products])
      plans = plans.products_like(params[:products])
    end

    unless params[:company].empty?
      report_collection = nil
      plan_collection = nil

      Auditor.company_like(params[:company]).each do |auditor|
        report_collection = (report_collection.nil?) ? auditor.reports : report_collection.or(auditor.reports)
        plan_collection = (plan_collection.nil?) ? auditor.plans : plan_collection.or(auditor.plans)
      end

      reports = reports.merge(report_collection) unless report_collection.nil?
      plans = plans.merge(plan_collection) unless plan_collection.nil?
    end

    unless params[:address].empty?
      report_collection = nil
      plan_collection = nil

      Auditor.address_like(params[:company]).each do |auditor|
        report_collection = (report_collection.nil?) ? auditor.reports : report_collection.or(auditor.reports)
        plan_collection = (plan_collection.nil?) ? auditor.plans : plan_collection.or(auditor.plans)
      end

      reports = reports.merge(report_collection) unless report_collection.nil?
      plans = plans.merge(plan_collection) unless plan_collection.nil?
    end

    @reports = reports.paginate(params[:report_page], 5)
    @plans = plans.paginate(params[:report_page], 5)

    render :search
  end

  def reserve_preview
    @plan = Plan.find(params[:id])
  end

  def reserve
    plan = Plan.find(params[:id])
    Reservation.create(price: plan.price, plan_id: plan.id, client_id: @client.id, auditor_id: plan.auditor.id)
    redirect_to client_search_path, notice: "Reservation completed successfully"
  end

  def purchase_preview
    @report = Report.find(params[:id])
  end

  def purchase
    report = Report.find(params[:id])
    Purchase.create(price: report.price, report_id: report.id, client_id: @client.id, auditor_id: report.auditor.id)
    redirect_to client_search_path, notice: "Purchase completed successfully"
  end

  def make_request
    @request = Request.new
    render :request
  end

  def request_send
    @request = Request.new(request_params)

    if @request.save
      redirect_to client_search_path, notice: "Request sent successfully"
    else
      render :request
    end
  end

  private
    def request_params
      params.require(:request).permit(:company, :address, :date, :products).merge(client_id: @client.id)
    end
end

app/controllers/client/general_controller.rb
class Client::GeneralController < ApplicationController
  before_action :client_authenticated?, except: [:create, :new]
  before_action :user_validated?, except: [:create, :new]
  before_action :set_client, except: [:new, :create]

  layout 'client', except: [:new, :create]

  def index
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      session[:user_id] = @client.id
      redirect_to client_dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def profile
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to client_profile_path
    else
      render :edit
    end
  end

  def delete
    @client.destroy
    redirect_to sign_out_path
  end

  def requests
    @requests = @client.requests
  end

  def reservations
    @reservations = @client.reservations
  end

  def purchases
    @purchases = @client.purchases
  end

  def rate_purchase
    purchase = Purchase.find(params[:id])

    if @client.purchases.include?(purchase)
      purchase.rate(params[:rating].to_i.clamp(0, 5))
    end

    redirect_to client_purchases_path, note: "Thanks for the rating"
  end

  def download_audit
    purchase = Purchase.find(params[:id])
    audit = purchase.report
    send_file File.open(File.join(Rails.root, audit.report.url)) if purchase.client_id = session[:user_id]
  end

  def accept_terms
    @client.update_attribute(:terms_of_service, true)
    redirect_to client_dashboard_path
  end

  def show_auditor
    @auditor = Auditor.find(params[:id])
  end

  private
    def client_params
      params.require(:client).permit(
        :name, :email, :address, :country, :company
      )
    end

    def set_client
      @client = Client.find(session[:user_id])
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :client_authenticated?, except: [:create, :new]
  before_action :client_validated?, except: [:create, :new, :accept_terms]

  layout 'client', except: [:new, :create]

  def index
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_signup_params)

    if @client.save
      session[:user_id] = @client.id
      redirect_to dashboard_client_path
    else
      render :new
    end
  end

  def show
  end

  def profile
    @client = Client.find(params[:id])
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to profile_auditor_path
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to sign_out_path
  end

  def messages
    @messages_sent = @client.messages_sent
    @messages_recieved = @client.messages_received.validated
  end

  def show_message
    @message = Message.find(params[:id])
    @message.update_attribute(:read, true) if params[:read].present?
  end

  def new_message
    @message = Message.new(source: @client)
    @audits = @client.purchases.collect { |purchase| purchase.report }
    @audits = @audits + @client.reservations.collect { |reservation| reservation.plan }
  end

  def send_message
    audit = Audit.find(params[:message][:audit_id])
    message = Message.new(source: @client, destiny: audit.auditor, audit: audit, body: params[:message][:body])

    if message.save
      redirect_to messages_client_path, notice: "Message sent"
    else
      @message = message
      @audits = @client.purchases.collect { |purchase| purchase.report }
      @audits = @audits + @client.reservations.collect { |reservation| reservation.plan }
      render :new_message
    end
  end

  def requests
    @requests = @client.requests
  end

  def reservations
    @reservations = @client.reservations
  end

  def purchases
    @purchases = @client.purchases
  end

  def rate_purchase
    purchase = Purchase.find(params[:id])

    if @client.purchases.include?(purchase)
      purchase.rate(params[:rating].to_i.clamp(0, 5))
    end

    redirect_to purchases_client_path, note: "Thanks for the rating"
  end

  def accept_terms
    @client.update_attribute(:terms_of_service, true)
    redirect_to dashboard_client_path
  end

  private
    def client_signup_params
      params.require(:client).permit(
        :password, :password_confirmation, :name,
        :email, :address,:company, :terms_of_service
      )
    end

    def client_params
      params.require(:client).permit(:name, :email, :address, :company)
    end

    def set_client
      @client = Client.find(session[:user_id])
    end
end

app/helpers/client/audits_helper.rb
module Client::AuditsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/audits/purchase_preview.html.erb
<h1>Report</h1>

<div class="form-material form-horizontal">

  <div class="form group">
    <label class="col-md-12">Date</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= l @report.date %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Products</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @report.products %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Price</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @report.price %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Summary</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @report.summary %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Rating</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @report.rating %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Upload date</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= l @report.upload_date %></p>
    </div>
  </div>

  <div id="paypal-button-container"></div>
</div>

<script>
  document.addEventListener('turbolinks:load', function() {
    var body = document.getElementsByTagName("body")[0]

    if (body.id == "audits_purchase_preview") {
      render_paypal(
        "<%= paypal_checkout_url %>",
        "<%= @report.price + @report.fee %>",
        "<%= @report.summary %>",
        "<%= paypal_execute_url %>",
        "<%= client_purchase_url %>",
        "Report"
      )
    }
  })
</script>

app/views/client/audits/request.html.erb
<h1>Audit request</h1>

<%= render "shared/error_messages", resource: @request %>

<div class="main">

<%= form_for @request, url: client_request_path do |f| %>

<div class="form-material form-horizontal">

  <div class="form-group">
    <%= f.label :company, class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :company, placeholder: "E-corp", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :address, placeholder: "Second street", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :products, class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :products, placeholder: "Paracetamol", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date, class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.date_field :date, min: Time.now + 1.day, class:"form-control form-control-line" %>
    </div>
  </div>

  <%= f.submit "Send audit request", class:"btn"%>
<% end %>

app/views/client/audits/reserve_preview.html.erb
<h1>Plan</h1>

<div class="form-material form-horizontal">

  <div class="form group">
    <label class="col-md-12">Company</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.auditor.company %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Address</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.auditor.address %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Products</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.products %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Planned audit date</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= l @plan.date %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Summary</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.summary %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Price</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.price %></p>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Proposed fee</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @plan.fee %></p>
    </div>
  </div>
  <div id="paypal-button-container"></div>
</div>

<script>
  document.addEventListener('turbolinks:load', function() {
    var body = document.getElementsByTagName("body")[0]

    if (body.id == "audits_reserve_preview") {
      render_paypal(
        "<%= paypal_checkout_url %>",
        "<%= @plan.price + @plan.fee %>",
        "<%= @plan.summary %>",
        "<%= paypal_execute_url %>",
        "<%= client_reserve_url %>",
        "Plan"
      )
    }
  })
</script>

app/views/client/audits/search.html.erb
<h1>Search audit</h1>

<%= form_tag client_search_path, method: :get do %>

<div class="form-material form-horizontal">

  <div class="form-group">
    <div class="col-md-12">
      <%= text_field_tag :query, @search_query, class:"form-control form-control-line" %>
    </div>
  <%= submit_tag "Search", class:"btn" %>
  </div>
</div>

<% end %>

<h2>Advanced search</h2>

<%= form_tag client_advanced_search_path, method: :get do %>

<div class="form-material form-horizontal">

    <div class="form-group">
      <%= label_tag :company, nil, class:"col-md-12" %>
      <div class="col-md-12">
        <%= text_field_tag :company, @search_company, class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :address, nil, class:"col-md-12" %>
      <div class="col-md-12">
        <%= text_field_tag :address, @search_address, class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :products, nil, class:"col-md-12" %>
      <div class="col-md-12">
        <%= text_field_tag :products, @search_products, class:"form-control form-control-line" %>
      </div>
    </div>

    <%= submit_tag "Advanced search", class:"btn" %>

</div>

<% end %>

<h1>Search results</h1>

<h2>Audit reports</h2>

<% if @reports.length == 0 %>
  <p>No reports available</p>
<% else %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Company</th>
        <th>Address</th>
        <th>Auditor</th>
        <th>Products</th>
        <th>Date</th>
        <th>Price</th>
        <th>Fee</th>
        <th>Rating</th>
        <th>Upload date</th>
        <th>Action<th>
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.auditor.company %></td>
          <td><%= report.auditor.address %></td>
          <td><%= link_to report.auditor.username, client_purchase_auditor_path(report.auditor.id) %></td>
          <td><%= report.products %></td>
          <td><%= l report.date %></td>
          <td><%= report.price %></td>
          <td><%= report.fee %></td>
          <td><%= report.rating %></td>
          <td><%= l report.upload_date %></td>
          <td><%= link_to "Purchase", client_purchase_preview_path(report.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <%= paginate @reports, param_name: :report_page %>
<% end %>

<h2>Planned audits</h2>

<% if @plans.count == 0 %>
  <p>No plans available</p>
<% else %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Company</th>
        <th>Address</th>
        <th>Auditor</th>
        <th>Products</th>
        <th>Date</th>
        <th>Price</th>
        <th>Fee<th>
      </tr>
    </thead>

    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><%= plan.auditor.company %></td>
          <td><%= plan.auditor.address %></td>
          <td><%= link_to plan.auditor.username, client_reservation_auditor_path(plan.auditor.id) %></td>
          <td><%= plan.products %></td>
          <td><%= l plan.date %></td>
          <td><%= plan.price %></td>
          <td><%= plan.fee %></td>
          <td><%= link_to "Reserve", client_reserve_preview_path(plan.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <%= paginate @plans, param_name: :plan_page %>
<% end %>

<h2>Audit request</h2>
<%= link_to "Send audit request", client_request_path, class:"btn" %>