config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/dashboard', to: 'general#index', as: 'dashboard'
    post '/create', to: 'general#create'

    get '/', to: 'general#index'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Users ###
    get '/user/:id', to: 'general#show_user', as: 'show_user'
    delete '/user/:id', to: 'general#delete_user', as: 'delete_user'
    post '/user/:id/validate', to: 'general#validate_user', as: 'validate_user'
    post '/user/:id/invalidate', to: 'general#invalidate_user', as: 'invalidate_user'

    ### Auditor ###
    post '/auditor/set_default_rating', to: 'general#set_default_auditor_rating', as: 'set_default_auditor_rating'
    post '/auditor/:id/download_cv', to: 'general#download_cv', as: 'download_auditor_cv'

    ### Audits ###
    get '/audit/:id/show', to: 'general#show_audit', as: 'show_audit'
    post '/audit/:id/validate', to: 'general#validate_audit', as: 'validate_audit'
    post '/audit/:id/invalidate', to: 'general#invalidate_audit', as: 'invalidate_audit'
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Report ###
    post '/report/set_default_rating', to: 'general#set_default_report_rating', as: 'set_default_report_rating'

    ### Notifications ###
    get '/notification/:id/show', to: 'general#show_notification', as: 'show_notification'

    ### Requests ###
    get '/request/:id/show', to: 'general#show_request', as: 'show_request'

    ### Terms ###
    resources :terms, controller: "terms"
    post 'terms/:id/select', to: "terms#select", as: "term_select"

    ### Contracts ###
    resources :contracts, controller: "contracts"
    post 'contracts/:id/select', to: "contracts#select", as: "contract_select"
    post 'contracts/:id/download', to: "contracts#download", as: "contract_download"
  end

  namespace :client do
    get '/', to: 'general#index', as: 'dashboard'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'
    post '/purchases/:id/rate', to: 'general#rate_purchase', as: 'rate_purchase'
    get '/purchase/:id/auditor', to: 'general#show_auditor', as: 'purchase_auditor'
    post '/purchase/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'
    get '/reservation/:id/auditor', to: 'general#show_auditor', as: 'reservation_auditor'

    scope :audits do
      get '/search', to: 'audits#search'
      get '/advanced_search', to: 'audits#advanced_search'

      ### Purchase ###
      get '/purchase/:id/preview', to: 'audits#purchase_preview', as: 'purchase_preview'
      get '/purchase/:id', to: 'audits#purchase', as: 'purchase'

      ### Reserve ###
      get '/reserve/:id/preview', to: 'audits#reserve_preview', as: 'reserve_preview'
      get '/reserve/:id', to: 'audits#reserve', as: 'reserve'

      ### Request ###
      get '/request', to: 'audits#make_request'
      post '/request', to: 'audits#request_send'
    end
  end

  get '/auditor', to: 'auditor/general#index'

  namespace :auditor do
    root 'general#index'
    get '/', to: 'general#index', as: 'dashboard'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    post '/profile/download_cv', to: 'general#download_cv', as: 'download_cv'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    post '/accept_terms', to: 'general#accept_terms'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Audits ###
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'

    ### Clients ###
    get '/show_client/:id', to: 'general#show_client', as: 'show_client'

    scope :audits do
      ### Report ###
      get '/show_report/:id', to: 'audits#show_report', as: 'show_report'
      get '/report', to: 'audits#report'
      post '/report', to: 'audits#report_send'
      get '/reports', to: 'audits#reports'

      ### Plan ###
      get '/show_plan/:id', to: 'audits#show_plan', as: 'show_plan'
      get '/plan', to: 'audits#plan'
      post '/plan', to: 'audits#plan_send'
      get '/plans', to: 'audits#plans'
    end
  end

  scope :paypal, as: 'paypal' do
    post '/checkout', to: 'paypal#checkout'
    post '/execute', to: 'paypal#execute'
  end

  get '/sign_in', to: 'website#new', as: 'sign_in'
  get '/sign_out', to: 'website#destroy', as: 'sign_out'
  get '/terms', to: 'website#terms', as: 'terms'
  post '/sign_in', to: 'website#create'
  post '/accept_terms', to: 'website#accept_terms'

  get '/new_forgot_password', to: 'website#new_forgot_password'
  post '/create_forgot_password', to: 'website#create_forgot_password'
  get '/new_credentials/:token', to: 'website#new_credentials', as: 'new_credentials'

  root 'website#index'
end

app/models/client.rb
class Client < NormalUser
  has_many :requests, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :reservations, dependent: :destroy

  def prefix
    'cus'
  end
end

app/controllers/client/audits_controller.rb
class Client::AuditsController < ApplicationController
  before_action :client_authenticated?
  before_action :user_validated?

  layout 'client'

  def search
    @search_query = params[:query]

    if params[:query] && !params[:query].empty?
      reports = Report.products_like(params[:query])
      plans = Plan.products_like(params[:query])

      Auditor.company_address_like(params[:query]).each do |auditor|
        reports = reports.or(auditor.reports)
        plans = plans.or(auditor.plans)
      end
    else
      reports = Report.all
      plans = Plan.all
    end

    @reports = reports.validated().paginate(params[:report_page], 5)
    @plans = plans.validated().not_expired().paginate(params[:report_page], 5)
  end

  def advanced_search
    @search_company = params[:company]
    @search_address = params[:address]
    @search_products = params[:products]

    reports = Report.validated()
    plans = Plan.validated().not_expired()

    unless params[:products].empty?
      reports = reports.products_like(params[:products])
      plans = plans.products_like(params[:products])
    end

    unless params[:company].empty?
      report_collection = nil
      plan_collection = nil

      Auditor.company_like(params[:company]).each do |auditor|
        report_collection = (report_collection.nil?) ? auditor.reports : report_collection.or(auditor.reports)
        plan_collection = (plan_collection.nil?) ? auditor.plans : plan_collection.or(auditor.plans)
      end

      reports = reports.merge(report_collection) unless report_collection.nil?
      plans = plans.merge(plan_collection) unless plan_collection.nil?
    end

    unless params[:address].empty?
      report_collection = nil
      plan_collection = nil

      Auditor.address_like(params[:company]).each do |auditor|
        report_collection = (report_collection.nil?) ? auditor.reports : report_collection.or(auditor.reports)
        plan_collection = (plan_collection.nil?) ? auditor.plans : plan_collection.or(auditor.plans)
      end

      reports = reports.merge(report_collection) unless report_collection.nil?
      plans = plans.merge(plan_collection) unless plan_collection.nil?
    end

    @reports = reports.paginate(params[:report_page], 5)
    @plans = plans.paginate(params[:report_page], 5)

    render :search
  end

  def reserve_preview
    @plan = Plan.find(params[:id])
  end

  def reserve
    plan = Plan.find(params[:id])
    Reservation.create(price: plan.price, plan_id: plan.id, client_id: @client.id, auditor_id: plan.auditor.id)
    redirect_to client_search_path, notice: "Reservation completed successfully"
  end

  def purchase_preview
    @report = Report.find(params[:id])
  end

  def purchase
    report = Report.find(params[:id])
    Purchase.create(price: report.price, report_id: report.id, client_id: @client.id, auditor_id: report.auditor.id)
    redirect_to client_search_path, notice: "Purchase completed successfully"
  end

  def make_request
    @request = Request.new
    render :request
  end

  def request_send
    @request = Request.new(request_params)

    if @request.save
      redirect_to client_search_path, notice: "Request sent successfully"
    else
      render :request
    end
  end

  private
    def request_params
      params.require(:request).permit(:company, :address, :date, :products).merge(client_id: @client.id)
    end
end

app/controllers/client/general_controller.rb
class Client::GeneralController < ApplicationController
  before_action :client_authenticated?, except: [:create, :new]
  before_action :user_validated?, except: [:create, :new]
  before_action :set_client, except: [:new, :create]

  layout 'client', except: [:new, :create]

  def index
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      session[:user_id] = @client.id
      redirect_to client_dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def profile
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to client_profile_path
    else
      render :edit
    end
  end

  def delete
    @client.destroy
    redirect_to sign_out_path
  end

  def requests
    @requests = @client.requests
  end

  def reservations
    @reservations = @client.reservations
  end

  def purchases
    @purchases = @client.purchases
  end

  def rate_purchase
    purchase = Purchase.find(params[:id])

    if @client.purchases.include?(purchase)
      purchase.rate(params[:rating].to_i.clamp(0, 5))
    end

    redirect_to client_purchases_path, note: "Thanks for the rating"
  end

  def download_audit
    purchase = Purchase.find(params[:id])
    audit = purchase.report
    send_file File.open(File.join(Rails.root, audit.report.url)) if purchase.client_id = session[:user_id]
  end

  def accept_terms
    @client.update_attribute(:terms_of_service, true)
    redirect_to client_dashboard_path
  end

  def show_auditor
    @auditor = Auditor.find(params[:id])
  end

  private
    def client_params
      params.require(:client).permit(
        :name, :email, :address, :country, :company
      )
    end

    def set_client
      @client = Client.find(session[:user_id])
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :client_authenticated?, except: [:create, :new]
  before_action :client_validated?, except: [:create, :new, :accept_terms]

  layout 'client', except: [:new, :create]

  def index
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_signup_params)

    if @client.save
      session[:user_id] = @client.id
      redirect_to dashboard_client_path
    else
      render :new
    end
  end

  def show
  end

  def profile
    @client = Client.find(params[:id])
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to profile_auditor_path
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to sign_out_path
  end

  def messages
    @messages_sent = @client.messages_sent
    @messages_recieved = @client.messages_received.validated
  end

  def show_message
    @message = Message.find(params[:id])
    @message.update_attribute(:read, true) if params[:read].present?
  end

  def new_message
    @message = Message.new(source: @client)
    @audits = @client.purchases.collect { |purchase| purchase.report }
    @audits = @audits + @client.reservations.collect { |reservation| reservation.plan }
  end

  def send_message
    audit = Audit.find(params[:message][:audit_id])
    message = Message.new(source: @client, destiny: audit.auditor, audit: audit, body: params[:message][:body])

    if message.save
      redirect_to messages_client_path, notice: "Message sent"
    else
      @message = message
      @audits = @client.purchases.collect { |purchase| purchase.report }
      @audits = @audits + @client.reservations.collect { |reservation| reservation.plan }
      render :new_message
    end
  end

  def requests
    @requests = @client.requests
  end

  def reservations
    @reservations = @client.reservations
  end

  def purchases
    @purchases = @client.purchases
  end

  def rate_purchase
    purchase = Purchase.find(params[:id])

    if @client.purchases.include?(purchase)
      purchase.rate(params[:rating].to_i.clamp(0, 5))
    end

    redirect_to purchases_client_path, note: "Thanks for the rating"
  end

  def accept_terms
    @client.update_attribute(:terms_of_service, true)
    redirect_to dashboard_client_path
  end

  private
    def client_signup_params
      params.require(:client).permit(
        :password, :password_confirmation, :name,
        :email, :address,:company, :terms_of_service
      )
    end

    def client_params
      params.require(:client).permit(:name, :email, :address, :company)
    end

    def set_client
      @client = Client.find(session[:user_id])
    end
end

app/helpers/client/audits_helper.rb
module Client::AuditsHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/index.html.erb
<h1>Search audit</h1>

<%= form_tag search_client_audits_path, method: :get do %>

<div class="form-material form-horizontal">

  <div class="form-group">
    <div class="col-md-12">
      <%= text_field_tag :query, @search_query, class:"form-control form-control-line" %>
    </div>
  <%= submit_tag "Search", class:"btn", style:"margin-top:1em;" %>
  </div>
</div>

<% end %>

<h2>Advanced search</h2>

<%= form_tag advanced_search_client_audits_path, method: :get do %>

<div class="form-material form-horizontal">

    <div class="form-group">
      <%= label_tag :company %>
      <div class="col-md-12">
        <%= text_field_tag :company, @search_company, class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :address %>
      <div class="col-md-12">
        <%= text_field_tag :address, @search_address, class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :products %>
      <div class="col-md-12">
        <%= text_field_tag :products, @search_products, class:"form-control form-control-line" %>
      </div>
    </div>

    <%= submit_tag "Advanced search", class:"btn" %>

</div>
<% end %>

app/views/clients/messages.html.erb
<h1>New message</h1>
<%= link_to "Send message", messages_new_client_path, class: "btn" %>

<h1>Messages sent</h1>

<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>Destiny</th>
      <th>Products</th>
      <th>Validated</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @messages_sent.each do |message| %>
      <tr>
        <td><%= message.destiny.username %></td>
        <td><%= message.audit.products %></td>
        <td><%= message.validated %></td>
        <td><%= link_to "See message", message_client_path(message.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<h1>Messages received</h1>

<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>Source</th>
      <th>Products</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @messages_recieved.each do |message| %>
      <tr>
        <td>
            <%= "<b>".html_safe unless message.read %>
            <%= message.source.username %>
        </td>
        <td>
            <%= "<b>".html_safe unless message.read %>
            <%= message.audit.products %>
        </td>
        <td>
            <%= "<b>".html_safe unless message.read %>
            <%= link_to "See message", message_client_path(message.id, read: true) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="/plugins/images/logo.png">
    <title>Colombo</title>
    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
    <!-- animation CSS -->
    <link href="/css/animate.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- color CSS -->
    <link href="/css/colors/default.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header">
    <!-- ============================================================== -->
    <!-- Preloader -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="/">
                        <!-- Logo icon image, you can use font-icon also --><b>
                        <!--This is dark logo icon--><img src="/plugins/images/logo.png" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="/plugins/images/colombo_Main.png" alt="home" class="light-logo" />
                    </a>
                </div>

            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- End Top Navigation -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
<div id="page-wrapper" style="margin-top: 0px;">
  <div class="container-fluid">
    <h1 class="box-title">Sign up as a Client</h1> </div>
    <div class="row">
      <div class="col-md-8" style="left:25px;">
        <div class="white-box">
          <%= render "shared/error_messages", resource: @client %>

          <%= form_for @client, url: sign_up_client_path do |f| %>
          <div class="form-material form-horizontal">
            <div class="form-group">
              <%= f.label :name, "Name", class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.text_field :name, placeholder: "Franky Howell Coleman", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :email, "Email", class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.text_field :email, placeholder: "francole@clmb.com", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :address, class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.text_field :address, placeholder: "6485 Bay Ave", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :company, class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.text_field :company, placeholder: "Platt Industries", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :password, "Password", class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.password_field :password, placeholder: "************", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, "Password confirmation", class:"col-md-12" %>
              <div class="col-md-12">
                <%= f.password_field :password_confirmation, placeholder: "************", class:"form-control form-control-line" %>
              </div>
            </div>

            <div class="form-group">
            <p>
                Accept <%= link_to "terms", terms_path %>?
                <%= f.check_box :terms_of_service %>
            </p>
            </div>

            <%= f.submit "Sign up", class:"btn", style:"margin-bottom:1em" %>
          <% end %>
        </div>
          <p class="change_link">
            Not a member yet ? Join us:
            <a href="/client/sign_up" class="to_register">Client</a> or
            <a href="/auditor/sign_up" class="to_register">Auditor</a> ?
          </p>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
</div>
<!-- ============================================================== -->
<!-- End Page Content -->
<!-- ============================================================== -->
</div>
<!-- /#wrapper -->
<!-- jQuery -->
<script src="/plugins/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Menu Plugin JavaScript -->
<script src="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
<!--slimscroll JavaScript -->
<script src="/js/jquery.slimscroll.js"></script>
<!--Wave Effects -->
<script src="/js/waves.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/js/custom.min.js"></script>
</body>

</html>

app/views/clients/new_message.html.erb
<h1>New message</h1>

<%= render "shared/error_messages", resource: @message %>

<%= form_for @message, url: messages_client_path do |f| %>
<div class="form-material form-horizontal">
  <div class="form-group">
    <%= f.label :audit %>
    <div class="col-md-12">
      <%= f.select :audit_id, options_from_collection_for_select(@audits, 'id', 'products'), class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <div class="col-md-12">
      <%= f.text_area :body, rows: 10, class:"form-control form-control-line" %>
    </div>
  </div>

  <%= f.submit "Send message", class:"btn" %>
</div>
<% end %>

app/views/clients/profile.html.erb
<h1>Profile</h1>

<p><b>Username: </b><%= @client.username %></p>
<p><b>First name: </b><%= @client.first_name %></p>
<p><b>Last name: </b><%= @client.last_name %></p>
<p><b>Email: </b><%= @client.email %></p>
<p><b>Address: </b><%= @client.address %></p>
<p><b>Company: </b><%= @client.company %></p>

app/views/clients/purchases.html.erb
<h1>Purchases list</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Products</th>
        <th>Price</th>
        <th>Company</th>
        <th>Address</th>
        <th>Date</th>
        <th>Rating</th>
      </tr>
    </thead>

    <tbody>
      <% @purchases.each do |purchase| %>
        <tr>
          <td><%= purchase.report.products %></td>
          <td><%= purchase.price %></td>
          <td><%= purchase.report.auditor.company %></td>
          <td><%= purchase.report.auditor.address %></td>
          <td><%= purchase.report.date %></td>
          <td>
            <% if purchase.rating == -1 %>
              <%= form_with url: rate_purchase_client_path(purchase.id) do |f| %>
                <%= f.number_field :rating, value: 0, min: 0, max: 5 %>
                <%= f.submit "Rate", class:"btn" %>
              <% end %>
            <% else %>
              <%= purchase.rating %>
            <% end %>
          </td>
          <td><%= link_to "Download", purchase.report.report.url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/show.html.erb
<h1>Profile</h1>
<div class="form-material form-horizontal">
  <div class="form group">
    <label class="col-md-12">Username</label>
    <div class="col-md-12">
    <p class="form-control form-control-line"><%= @client.username %></p>
    </div>
  </div>
  <div class="form group">
    <label class="col-md-12">Name</label>
    <div class="col-md-12">
    <p class="form-control form-control-line"><%= @client.name %></p>
    </div>
  </div>
  <div class="form group">
    <label class="col-md-12">Email</label>
    <div class="col-md-12">
    <p class="form-control form-control-line"><%= @client.email %></p>
    </div>
  </div>
  <div class="form group">
    <label class="col-md-12">Address</label>
    <div class="col-md-12">
      <p class="form-control form-control-line"><%= @client.address %></p>
    </div>
  </div>
  <div class="form group">
    <label class="col-md-12">Company</label>
    <div class="col-md-12">
    <p class="form-control form-control-line"><%= @client.company %></p>
    </div>
  </div>
</div>

<button class="btn"><%= link_to "Edit account", edit_client_path %></button>
<button class="btn"><%= link_to "Delete account", client_path, method: :delete, data: { confirm: 'Are you sure?' } %></button>