config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/dashboard', to: 'general#index', as: 'dashboard'
    post '/create', to: 'general#create'

    get '/', to: 'general#index'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Users ###
    get '/user/:id', to: 'general#show_user', as: 'show_user'
    delete '/user/:id', to: 'general#delete_user', as: 'delete_user'
    post '/user/:id/validate', to: 'general#validate_user', as: 'validate_user'
    post '/user/:id/invalidate', to: 'general#invalidate_user', as: 'invalidate_user'

    ### Auditor ###
    post '/auditor/set_default_rating', to: 'general#set_default_auditor_rating', as: 'set_default_auditor_rating'
    post '/auditor/:id/download_cv', to: 'general#download_cv', as: 'download_auditor_cv'

    ### Audits ###
    get '/audit/:id/show', to: 'general#show_audit', as: 'show_audit'
    post '/audit/:id/validate', to: 'general#validate_audit', as: 'validate_audit'
    post '/audit/:id/invalidate', to: 'general#invalidate_audit', as: 'invalidate_audit'
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Report ###
    post '/report/set_default_rating', to: 'general#set_default_report_rating', as: 'set_default_report_rating'

    ### Notifications ###
    get '/notification/:id/show', to: 'general#show_notification', as: 'show_notification'

    ### Requests ###
    get '/request/:id/show', to: 'general#show_request', as: 'show_request'

    ### Terms ###
    resources :terms, controller: "terms"
    post 'terms/:id/select', to: "terms#select", as: "term_select"

    ### Contracts ###
    resources :contracts, controller: "contracts"
    post 'contracts/:id/select', to: "contracts#select", as: "contract_select"
    post 'contracts/:id/download', to: "contracts#download", as: "contract_download"
  end

  namespace :client do
    get '/', to: 'general#index', as: 'dashboard'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'
    post '/purchases/:id/rate', to: 'general#rate_purchase', as: 'rate_purchase'
    get '/purchase/:id/auditor', to: 'general#show_auditor', as: 'purchase_auditor'
    post '/purchase/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'
    get '/reservation/:id/auditor', to: 'general#show_auditor', as: 'reservation_auditor'

    scope :audits do
      get '/search', to: 'audits#search'
      get '/advanced_search', to: 'audits#advanced_search'

      ### Purchase ###
      get '/purchase/:id/preview', to: 'audits#purchase_preview', as: 'purchase_preview'
      get '/purchase/:id', to: 'audits#purchase', as: 'purchase'

      ### Reserve ###
      get '/reserve/:id/preview', to: 'audits#reserve_preview', as: 'reserve_preview'
      get '/reserve/:id', to: 'audits#reserve', as: 'reserve'

      ### Request ###
      get '/request', to: 'audits#make_request'
      post '/request', to: 'audits#request_send'
    end
  end

  get '/auditor', to: 'auditor/general#index'

  namespace :auditor do
    root 'general#index'
    get '/', to: 'general#index', as: 'dashboard'
    get '/profile', to: 'general#show'
    delete '/profile', to: 'general#delete'
    get '/profile/edit', to: 'general#edit'
    patch '/profile/edit', to: 'general#update'
    post '/profile/download_cv', to: 'general#download_cv', as: 'download_cv'
    get '/sign_up', to: 'general#new'
    post '/sign_up', to: 'general#create'
    post '/accept_terms', to: 'general#accept_terms'

    #Conversations
    post '/conversations', to: 'general#create_conversation'
    get '/conversations', to: 'general#conversation_index'
    get '/conversations/:id', to: 'general#show_conversation', as: 'show_conversation'
    post '/message', to: 'general#create_message'

    ### Audits ###
    post '/audit/:id/download', to: 'general#download_audit', as: 'download_audit'

    ### Purchases ###
    get '/purchases', to: 'general#purchases'

    ### Requests ###
    get '/requests', to: 'general#requests'

    ### Reservations ###
    get '/reservations', to: 'general#reservations'

    ### Clients ###
    get '/show_client/:id', to: 'general#show_client', as: 'show_client'

    scope :audits do
      ### Report ###
      get '/show_report/:id', to: 'audits#show_report', as: 'show_report'
      get '/report', to: 'audits#report'
      post '/report', to: 'audits#report_send'
      get '/reports', to: 'audits#reports'

      ### Plan ###
      get '/show_plan/:id', to: 'audits#show_plan', as: 'show_plan'
      get '/plan', to: 'audits#plan'
      post '/plan', to: 'audits#plan_send'
      get '/plans', to: 'audits#plans'
    end
  end

  scope :paypal, as: 'paypal' do
    post '/checkout', to: 'paypal#checkout'
    post '/execute', to: 'paypal#execute'
  end

  get '/sign_in', to: 'website#new', as: 'sign_in'
  get '/sign_out', to: 'website#destroy', as: 'sign_out'
  get '/terms', to: 'website#terms', as: 'terms'
  post '/sign_in', to: 'website#create'
  post '/accept_terms', to: 'website#accept_terms'

  get '/new_forgot_password', to: 'website#new_forgot_password'
  post '/create_forgot_password', to: 'website#create_forgot_password'
  get '/new_credentials/:token', to: 'website#new_credentials', as: 'new_credentials'

  root 'website#index'
end

app/controllers/admin/general_controller.rb
class Admin::GeneralController < ApplicationController
  before_action :admin_authenticated?
  before_action :set_user, only: [:show_user, :validate_user, :invalidate_user, :delete_user, :download_cv]
  before_action :set_audit, only: [:show_audit, :validate_audit, :download_audit]

  include ConversationHandler

  layout 'admin'

  def index(admin=Admin.new)
    @admin = admin
    @auditors = Auditor.order(:validated).page(params[:auditor_page]).per(5)
    @clients = Client.order(:validated).page(params[:client_page]).per(5)
    @reports = Report.order(:validated).page(params[:report_page]).per(5)
    @plans = Plan.order(:validated).page(params[:plan_page]).per(5)
    @requests = Request.order(:created_at).page(params[:request_page]).per(5)
    @notifications = AdminNotification.order(:created_at).order(:read).page(params[:notification_page]).per(5)
  end

  def create
    @admin = Admin.new(admin_params)

    if @admin.save
      redirect_to admin_dashboard_path
    else
      index(@admin)
      render :index
    end
  end

  def show_user
  end

  def show_audit
  end

  def show_request
    @request = Request.find(params[:id])
  end

  def show_notification
    @notification = AdminNotification.find(params[:id])
    @notification.mark_as_read()
  end

  def validate_user
    @user.update_column(:validated, true)

    redirect_to request.referrer unless request.referrer.nil?
  end

  def invalidate_user
    @user.update_column(:validated, false)

    redirect_to request.referrer unless request.referrer.nil?
  end

  def delete_user
    @user.destroy

    redirect_to admin_dashboard_path
  end

  def validate_audit
    @audit.update_column(:validated, true)

    redirect_to request.referrer unless request.referrer.nil?
  end

  def invalidate_audit
    @audit.update_column(:validated, false)

    redirect_to request.referrer unless request.referrer.nil?
  end

  def set_default_report_rating
    Report::set_default_rating(params[:rating])

    redirect_to admin_dashboard_path
  end

  def set_default_auditor_rating
    Auditor::set_default_rating(params[:rating])

    redirect_to dashboard_admin_path
  end

  def download_audit
    send_file File.open(File.join(Rails.root, @audit.report.url))
  end

  def download_cv
    send_file File.open(File.join(Rails.root, @user.cv.url))
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def set_audit
      @audit = Audit.find(params[:id])
    end

    def admin_params
      params.require(:admin).permit(:email)
    end
end

app/controllers/auditor/audits_controller.rb
class Auditor::AuditsController < ApplicationController
  before_action :auditor_authenticated?
  before_action :user_validated?

  layout 'auditor'

  def report
    @report = Report.new
  end

  def report_send
    @report = Report.new(report_params)

    if @report.save
      redirect_to auditor_reports_path, notice: "Report sent successfully"
    else
      render :report
    end
  end

  def reports
    @reports = @auditor.reports.order(:date)
  end

  def show_report
    @report = Report.find(params[:id])
  end

  def plan
    @plan = Plan.new
  end

  def plan_send
    @plan = Plan.new(plan_params)

    if @plan.save
      redirect_to auditor_plans_path, notice: "Plan sent successfully"
    else
      render :plan
    end
  end

  def plans
    @plans = @auditor.plans.order(:date)
  end

  def show_plan
    @plan = Plan.find(params[:id])
  end

  private
    def report_params
      params.require(:report)
        .permit(:products, :price, :summary, :report).merge(auditor_id: @auditor.id)
    end

    def plan_params
      params.require(:plan)
        .permit(:products, :price, :date, :summary, :fee).merge(auditor_id: @auditor.id)
    end
end

app/controllers/auditor/general_controller.rb
class Auditor::GeneralController < ApplicationController
  before_action :auditor_authenticated?, except: [:create, :new]
  before_action :user_validated?, except: [:create, :new]

  include ConversationHandler

  layout 'auditor', except: [:new, :create]

  def index
  end

  def new
    @auditor = Auditor.new
  end

  def create
    @auditor = Auditor.new(auditor_signup_params)

    if @auditor.save
      session[:user_id] = @auditor.id
      redirect_to auditor_dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @auditor.update_attributes(auditor_params)
      @auditor.notify_cv_update if auditor_params[:cv].present?

      redirect_to auditor_profile_path
    else
      render :edit
    end
  end

  def destroy
    @auditor.destroy
    redirect_to sign_out_path
  end

  def purchases
    @purchases = @auditor.purchases
  end

  def reservations
    @reservations = @auditor.reservations
  end

  def requests
    @requests = []

    Request.all.each do |request|
      like_address = !(@auditor.address =~ /.*#{request.address}.*/).nil?
      like_company = !(@auditor.company =~ /.*#{request.company}.*/).nil?

      if like_address && like_company
        @requests << request
      end
    end
  end

  def show_client
    @client = Client.find(params[:id])
  end

  def download_audit
    @audit = Audit.find(params[:id])
    send_file File.open(File.join(Rails.root, @audit.report.url)) if @audit.auditor_id = session[:user_id]
  end

  def download_cv
    user = User.find(session[:user_id])
    send_file File.open(File.join(Rails.root, user.cv.url))
  end

  private
    def auditor_signup_params
      params.require(:auditor).permit(
        :name, :email, :qualifications, :cv, :address, :company, :country, :cv_cache
      )
    end

    def auditor_params
      params.require(:auditor).permit(
        :name, :email, :qualifications, :password, :password_confirmation,
        :address, :company, :country, :cv, :cv_cache
      )
    end
end

app/controllers/auditors_controller.rb
class AuditorsController < ApplicationController
  before_action :auditor_authenticated?, except: [:create, :new]
  before_action :auditor_validated?, except: [:create, :new, :accept_terms]

  layout 'auditor', except: [:new, :create]

  def index
  end

  def new
    @auditor = Auditor.new
  end

  def create
    @auditor = Auditor.new(auditor_signup_params)

    if @auditor.save
      session[:user_id] = @auditor.id
      redirect_to dashboard_auditor_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @auditor.update_attributes(auditor_params)
      redirect_to profile_auditor_path
    else
      render :edit
    end
  end

  def destroy
    @auditor.destroy
    redirect_to sign_out_path
  end

  def purchases
    @purchases = @auditor.purchases
  end

  def reservations
    @reservations = @auditor.reservations
  end

  def requests
    @requests = []

    Request.each do |request|
      like_address = !(@auditor.address =~ /.*#{request.address}.*/).nil?
      like_company = !(@auditor.company =~ /.*#{request.company}.*/).nil?

      if like_address && like_company
        @requests << request
      end
    end
  end

  def messages
    @messages_sent = @auditor.messages_sent
    @messages_recieved = @auditor.messages_received.validated
  end

  def show_message
    @message = Message.find(params[:id])
    @message.update_attribute(:read, true) if params[:read].present?
  end

  def new_message
    @message = Message.new
    @clients_audits = @auditor.purchases.collect { |purchase| [ "Products: #{purchase.report.products} Client: #{purchase.client.username}", "#{purchase.client_id}_#{purchase.report_id}" ] }
    @clients_audits = @clients_audits + @auditor.reservations.collect { |reservation| [ "Products: #{reservation.plan.products} Client: #{reservation.client.username}", "#{reservation.client_id}_#{reservation.plan_id}" ] }
  end

  def send_message
    client_audit_ids = params[:message][:client_audit_ids].split('_')
    client = Client.find(client_audit_ids[0].to_i)
    audit = Audit.find(client_audit_ids[1].to_i)

    message = Message.new(source: @auditor, destiny: client, audit: audit, body: params[:message][:body])

    if message.save
      redirect_to messages_auditor_path, notice: "Message sent"
    else
      @message = message
      @clients_audits = @auditor.purchases.collect { |purchase| [ purchase.report.products, purchase.client_id ] }
      @clients_audits = @clients_audits + @auditor.reservations.collect { |reservation| [ reservation.plan.products, reservation.client_id ] }
      render :new_message
    end
  end

  def show_client
    @client = Client.find(params[:id])
  end

  def accept_terms
    @auditor.update_attribute(:terms_of_service, true)
    redirect_to dashboard_auditor_path
  end

  private
    def auditor_signup_params
      params.require(:auditor).permit(:name, :email, :qualifications, :cv, :password, :password_confirmation, :terms_of_service, :address, :company)
    end

    def auditor_params
      params.require(:auditor).permit(:name, :email, :qualifications)
    end
end

app/controllers/client/general_controller.rb
class Client::GeneralController < ApplicationController
  before_action :client_authenticated?, except: [:create, :new]
  before_action :user_validated?, except: [:create, :new]
  before_action :set_client, except: [:new, :create]

  layout 'client', except: [:new, :create]

  def index
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      session[:user_id] = @client.id
      redirect_to client_dashboard_path
    else
      render :new
    end
  end

  def show
  end

  def profile
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      redirect_to client_profile_path
    else
      render :edit
    end
  end

  def delete
    @client.destroy
    redirect_to sign_out_path
  end

  def requests
    @requests = @client.requests
  end

  def reservations
    @reservations = @client.reservations
  end

  def purchases
    @purchases = @client.purchases
  end

  def rate_purchase
    purchase = Purchase.find(params[:id])

    if @client.purchases.include?(purchase)
      purchase.rate(params[:rating].to_i.clamp(0, 5))
    end

    redirect_to client_purchases_path, note: "Thanks for the rating"
  end

  def download_audit
    purchase = Purchase.find(params[:id])
    audit = purchase.report
    send_file File.open(File.join(Rails.root, audit.report.url)) if purchase.client_id = session[:user_id]
  end

  def accept_terms
    @client.update_attribute(:terms_of_service, true)
    redirect_to client_dashboard_path
  end

  def show_auditor
    @auditor = Auditor.find(params[:id])
  end

  private
    def client_params
      params.require(:client).permit(
        :name, :email, :address, :country, :company
      )
    end

    def set_client
      @client = Client.find(session[:user_id])
    end
end

app/helpers/auditor_helper.rb
module AuditorHelper
end

app/views/auditor/general/edit.html.erb
<h1>Edit account details</h1>

<%= render "shared/error_messages", resource: @auditor %>

<%= form_for @auditor, url: auditor_profile_edit_path, multipart: true do |f| %>
<div class="form-material form-horizontal">
  <div class="form-group">
    <%= f.label :name, "Name", class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :name, placeholder: "Franky Howell Coleman", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email", class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.email_field :email, placeholder: "francole@clmb.com", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form group">
    <label class="col-md-12">Country</label>
    <div class="col-md-12">
      <%= f.country_select :country, {}, class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :company, "Company", class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :company, placeholder: "Platt Industries", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, "Adress", class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :address, placeholder: "6485 Bay Ave", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :qualifications, "Qualifications", class:"col-md-12" %>
    <div class="col-md-12">
      <%= f.text_field :qualifications, placeholder: "Senior agent", class:"form-control form-control-line" %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label :password, "Password", class:"col-md-12" %>

      <div class="col-md-12">
        <%= f.password_field :password, placeholder: "************", class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Password confirmation", class:"col-md-12" %>

      <div class="col-md-12">
        <%= f.password_field :password_confirmation, placeholder: "************", class:"form-control form-control-line" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :cv, "CV", class:"col-md-12" %>
      <div class="col-md-12">
        <%= f.file_field :cv, class:"form-control form-control-line" %>
        <%= f.hidden_field :cv_cache, class:"form-control form-control-line" %>
      </div>
    </div>
</div>
  <%= f.submit "Update account", class:"btn" %>
<% end %>

app/views/auditor/general/index.html.erb
<%= link_to "Send audit report", auditor_report_path, class: "btn" %>
<%= link_to "Send audit plan", auditor_plan_path, class:"btn" %>

app/views/auditor/general/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="/plugins/images/logo.png">
    <title>Colombo</title>
    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
    <!-- animation CSS -->
    <link href="/css/animate.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- color CSS -->
    <link href="/css/colors/default.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header">
    <!-- ============================================================== -->
    <!-- Preloader -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Wrapper -->
    <!-- ============================================================== -->
    <div id="wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <!-- End Top Navigation -->
        <!-- ============================================================== -->

        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
                <h1 class="box-title" style="text-align:center">Sign up as a Auditor</h1> </div>
                <div class="row">
                    <div class="col-md-8" style="left:25px;">
                        <div class="pink-box">
                            <%= render "shared/error_messages", resource: @auditor %>

                            <%= form_for @auditor, url: auditor_sign_up_path, multipart: true do |f| %>
                            <div class="form-material form-horizontal">
                                <div class="form-group">
                                  <%= f.label :name, "Full name", class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.text_field :name, placeholder: "Full name", class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <div class="form-group">
                                  <%= f.label :email, "Email", class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.text_field :email, placeholder: "Email", class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <div class="form-group">
                                  <%= f.label :address, class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.text_field :address, placeholder: "Address", class:"form-control form-control-line" %>
                                  </div>
                                </div>


                                <div class="form-group">
                                  <%= f.label :company, class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.text_field :company, placeholder: "Company", class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <div class="form-group">
                                  <%= f.label :qualifications, "Qualifications", class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.text_field :qualifications, placeholder: "Qualifications", class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <div class="form-group">
                                  <label class="col-md-12">Country</label>

                                  <div class="col-md-12">
                                    <%= f.country_select :country, {}, class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <div class="form-group">
                                  <%= f.label :cv, "CV", class:"col-md-12" %>
                                  <div class="col-md-12">
                                    <%= f.file_field :cv, class:"form-control form-control-line" %>
                                    <%= f.hidden_field :cv_cache, class:"form-control form-control-line" %>
                                  </div>
                                </div>

                                <%= f.submit "Sign up", class:"btn", style:"margin-bottom:1em" %>
                            <% end %>
                          </div>
                            <p class="change_link">
                              Not a member yet ? Join us:
                              <%= link_to "Client", client_sign_up_path %> or
                              <%= link_to "Auditor", auditor_sign_up_path %> ?
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="/plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
    <!--slimscroll JavaScript -->
    <script src="/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="/js/waves.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/js/custom.min.js"></script>
</body>

</html>

app/views/auditor/general/purchases.html.erb
<h1>Sold reports</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Client</th>
        <th>Products</th>
      </tr>
    </thead>

    <tbody>
      <% @purchases.each do |purchase| %>
        <tr>
          <td><%= link_to purchase.client.username, auditor_show_client_path(purchase.client_id) %></td>
          <td><%= purchase.report.products %></td>
          <td><%= link_to "Report", auditor_show_report_path(purchase.report_id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/auditor/general/requests.html.erb
<h1>Request listing</h1>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
            <th>Products</th>
            <th>Company</th>
            <th>Client</th>
            </tr>
        </thead>

        <tbody>
            <% @requests.each do |request| %>
            <tr>
                <td><%= request.products %></td>
                <td><%= request.company %></td>
                <td><%= request.address %></td>
                <td><%= l request.date %></td>
                <td><%= link_to request.client.username, auditor_show_client_path(request.client_id) %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/auditor/general/reservations.html.erb
<h1>Booked audit plans</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Client</th>
        <th>Products</th>
      </tr>
    </thead>

    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= link_to reservation.client.username, auditor_show_client_path(reservation.client_id) %></td>
          <td><%= reservation.plan.products %></td>
          <td><%= link_to "Plan", auditor_show_plan_path(reservation.plan_id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/auditor/general/show.html.erb
  <h1>Profile</h1>
  <div class="form-material form-horizontal">
    <div class="form group">
      <label class="col-md-12">Username</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.username %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Rating</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.rating %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Registered since</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= l @auditor.created_at.to_date %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Name</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.name %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Country</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.country_name %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Email</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.email %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Company</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.company %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Address</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.address %></p>
      </div>
    </div>

    <div class="form group">
      <label class="col-md-12">Qualifications</label>
      <div class="col-md-12">
        <p class="form-control form-control-line"><%= @auditor.qualifications %></p>
      </div>
    </div>
    <div class="form group">
      <%= link_to "Download CV", auditor_download_cv_path, method: :post %>
    </div>
  </div>

  <button class="btn"><%= link_to "Edit account", auditor_profile_edit_path %></button>
  <button class="btn"><%= link_to 'Delete account', auditor_profile_path, method: :delete, data: { confirm: 'Are you sure?' } %></button>